### ISSUE TITLE
`allReady` does not work.

### ISSUE THREAD

**Issue by ElvishJerricco** [ccorcos/meteor-subs-cache#20] opened 2016-06-07 04:28 UTC
With subs-cache 0.1.0 and meteor 1.2 or 1.3, it appears that the `allReady` reactive variable is not successfully set when subscriptions become ready.

<img width="1440" alt="screen shot 2016-06-07 at 12 25 45 am" src="https://cloud.githubusercontent.com/assets/1365692/15845967/72f0f9a2-2c46-11e6-830c-e8cd73cba98a.png">

**Comment by paranoico** [comment] 2016-12-15 23:54
Hello @ElvishJerricco , I would like to know if this issue is related to setTimers problem.

I am retaking subs-cache maintenance and would like to know if it is still an issue.

**Comment by ElvishJerricco** [comment] 2016-12-16 00:48
Sorry, this project has mostly left my brain. I don't think I can help much.

**Comment by paranoico** [comment] 2016-12-16 20:27
@ElvishJerricco Thanks for your prompt answer, I am closing the issue for now.

Best Regards.

**Comment by nicooprat** [comment] 2017-03-02 09:34
Has anyone found a solution? Looks like I'm having the same issue.

**Comment by paranoico** [comment] 2017-04-13 18:56
Reopening until I confirm there is no issue with new JS version.

**Comment by nicooprat** [comment] 2017-10-12 17:11
Any fix planned? Thanks!

**Comment by nicooprat** [comment] 2017-10-21 19:39
When checking on https://github.com/ccorcos/meteor-subs-cache/pull/41 and tried with latest code, `allReady.get()` was working as expected.

**Comment by paranoico** [comment] 2017-10-23 17:20
Thanks a lot @nicooprat

**Comment by nicooprat** [comment] 2017-11-04 22:13
To be more precise, it's now reactive, but sometimes `allReady.get()` still returns false although all subscriptions seem ready. I can't remember where I got this bit of code, but this workaround works (proving that `allReady.get()` is actually wrong): 

```js
_(Subs.cache).chain().values().map((x) => x.ready()).reduce((a,b) => a && b).value()
```

`Subs` being the var of my (only) SubsCache object of course.

**Comment by paranoico** [comment] 2017-11-05 03:20
Hello,
So the issue still persist, right?

**Comment by nicooprat** [comment] 2017-11-05 09:03
Yes, looks like... It happens sometimes, can't get a reproducible test case for now :/

**Comment by paranoico** [comment] 2018-04-11 15:10
We have seen different behavior than can be originated from this component and seems to be related to Meteor update, mainly the differences come when upgrading from Meteor 1.5.x to 1.6.x.

Here we have no more information on how to reproduce int this, we are currently still trying to find the specific code woth problem.

**Comment by janat08** [comment] 2018-04-11 15:14
https://github.com/Blockrazor/blockrazor/pull/1052 reproduces this on route [/currency/:slug].

**Comment by thebarty** [comment] 2018-08-24 09:32
Same problem over here. 

Subscribing like
```
// using Blaze Components
onCreated() {
  super.onCreated()
  // TemplateLevel autorun
  this.autorun(() => {
    globalSubscriptionManager.subscribe('sub1')
    globalSubscriptionManager.subscribe('sub2')
  })
}
```

**Problem: globalSubscriptionManager.ready() acts unreliable and after clicking a few links in the ui returns "false"**

**Comment by paranoico** [comment] 2018-08-24 17:29
Do you have more information on how to reproduce it? It would be helpful.

**Comment by thebarty** [comment] 2018-08-27 06:28
Hi guys,

just letting you know: I switched to using the original https://github.com/kadirahq/subs-manager which works much more stable for me.

There seems to be something wrong in the codebase.

The bug exists in this package and also in https://atmospherejs.com/blockrazor/subscache-c4.

**Comment by paranoico** [comment] 2018-08-27 16:32
Hello @thebarty,

Sorry but what globalSubscriptionManager do you mean?

**Comment by paranoico** [comment] 2019-02-20 23:26
Closing again for now, after PR from @ulion 

Thank you.

**Closed by paranoico** 2019-02-20 23:26 UTC
